services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /mnt/disk/books/docker-calibre-web/library:/config/Calibre Library
    ports:
      - 8083:8083
    restart: unless-stopped
